services:

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    image: order-service:latest
    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__Database=Host=order-db;Port=5432;Database=order;Username=order_user;Password=order_pw
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  order-db:
    image: postgres:18-alpine
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pw
      POSTGRES_DB: order
    volumes:
      - order_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  order_pgdata:
  inventory_pgdata:

networks:
  backend:
